### ISSUE TITLE
Please switch to .taskcluster.yml version 1

### ISSUE THREAD

**Issue by djmitche** [mozilla-platform-ops/cloud-image-builder#10]
In taskcluster/taskcluster#4098 we are dropping support for v0.  The quickstart is probably a good place to start generating a new file.

**Comment by jwmoss** [comment]
Closing older issue, I believe this has been resolved [here](https://github.com/mozilla-platform-ops/cloud-image-builder/commit/08d6dd991b703770fd2bff7af00f6662f3b3562d)
